version: '3'
networks:
  nrv.net:
    driver: bridge


services:

  ##############################
  ### BDD : bases de données ###
  ##############################
  nrv.catalogue.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./catalogue.env
    ports:
      - '32100:3306'
    networks:
      - nrv.net
    volumes:
      - ../api/catalogue.nrv/sql:/var/sql

  nrv.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '32102:3306'
    networks:
      - nrv.net
    volumes:
      - ../api/auth.nrv/sql:/var/sql


  ############################################
  ### service administration des bases sql ###
  ############################################
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '32103:8080'
    networks:
      - nrv.net


  ######################################
  ### API : les API de l'application ###
  ######################################
  api.nrv.catalogue:
    image: 'canals/php:latest'
    env_file: ./catalogue.env
    ports:
      - '32104:80'
    volumes:
      - ../api/catalogue.nrv/public:/var/www/html
      - ../api/catalogue.nrv:/var/www
    working_dir: /var/www
    networks:
      nrv.net:
        aliases:
          - catalogue.nrv.local
    depends_on:
      - nrv.catalogue.db


  api.nrv.auth:
    image: 'canals/php:latest'
    env_file: ./auth.env
    ports:
      - '32106:80'
    volumes:
      - ../api/auth.nrv/public:/var/www/html
      - ../api/auth.nrv:/var/www
      - ./auth.env:/config/.env
    working_dir: /var/www
    networks:
      nrv.net:
        aliases:
          - auth.nrv.local
    depends_on:
      - nrv.auth.db

  gateway.nrv:
    image: 'canals/php:latest'
    env_file: ./gate.env
    ports:
      - '32107:80'
    volumes:
      - ../api/gateway.nrv/public:/var/www/html
      - ../api/gateway.nrv:/var/www
      - ./gate.env:/config/.env
    working_dir: /var/www
    networks:
      nrv.net:
        aliases:
          - gateway.nrv.local
    depends_on:
      - api.nrv.auth
      - api.nrv.catalogue


  ##########################################
  ### WEB : service web de l'application ###
  ##########################################
  web:
    image: httpd:latest
    ports:
      - "32108:80"
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache-iutnc.univ-lorraine.fr:3128
    volumes:
      - ../web/public:/usr/local/apache2/htdocs/
      - ../web/src:/usr/local/apache2/htdocs/src/
    networks:
      - nrv.net
    depends_on:
      - gateway.nrv
